services:
  # 1. Máy chủ Cơ sở dữ liệu MongoDB cho Order Service
  order-db:
    image: mongo:latest
    ports:
      - "27017:27017"

  # 2. Dịch vụ Sản phẩm
  product-service:
    build: ./web-ban-nuoc
    ports:
      - "3001:3001"

  # 3. Dịch vụ Đặt hàng (Khai báo thêm là nó phụ thuộc vào order-db)
  order-service:
    build: ./order-service
    ports:
      - "3002:3002"
    depends_on:
      - order-db

  # 4. API Gateway (Lễ tân)
  api-gateway:
    build: ./api-gateway
    ports:
      - "3000:3000"
    depends_on:
      - product-service
      - order-service