services:
  # 1. Máy chủ Cơ sở dữ liệu MongoDB cho Product Service
  product-db:
    image: mongo:latest
    ports:
      - "27018:27017"

  # 2. Máy chủ Cơ sở dữ liệu MongoDB cho Order Service
  order-db:
    image: mongo:latest
    ports:
      - "27017:27017"

  # 2. Dịch vụ Sản phẩm (Chứa giao diện Web)
  product-service:
    build: ./web-ban-nuoc
    ports:
      - "3001:3001"

  # 3. Dịch vụ Đặt hàng (Có kết nối Database)
  order-service:
    build: ./order-service
    ports:
      - "3002:3002"
    depends_on:
      - order-db

  # 4. DỊCH VỤ THANH TOÁN (MỚI BỔ SUNG)
  payment-service:
    build: ./payment-service
    ports:
      - "3003:3003"

  # 5. API Gateway (Lễ tân)
  api-gateway:
    build: ./api-gateway
    ports:
      - "3000:3000"
    depends_on:
      - product-service
      - order-service
      - payment-service